name: Build and Package Electron App

on:
  push:
    branches: [ main ] 
  workflow_dispatch: 

jobs:
  build_windows:
    runs-on: windows-2022 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install Dependencies
        run: npm install

      - name: Build Application (Create .exe)
        run: npm run dist

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: release-builds/
